google/keytransparency

Makefile, core/client/ctlog/client_ct.go, core/queue/queue.go, core/signer/signer.go, core/tree/sparse/verifier/verifier_test.go, impl/google/authentication/google.go
Fix `gofmt` and `misspell` errors.
=> Fix go report errors

impl/etcd/queue/etcd.go
Txn only returns ErrDuplicateKey if the same key is modified twice in the
same block; the version/create/mod value should be compared to 0 instead.
=> queue: check for duplicate key in transaction

.travis.yml, README.md
=> Create an Initial travis-ci Script

README.md
=> Include Go version number in README

CONTRIBUTING.md
=> fix presubmit stanza in the guidelines

cmd/keytransparency-client/cmd/keys.go, core/crypto/keymaster/keymaster.go, core/crypto/keymaster/keymaster_test.go, core/signatures/p256/ecdsa_p256.go
=> Move core/keystore to core/crypto/keymaster

core/mutator/entry/entry.go
Before returning, masked errors are logged in `CheckMutation`. Logged messages are shown in the running binary's log, i.e., frontend, backend, or even client.
Partial #494.
=> Log Errors in CheckMutation

cmd/keytransparency-client/grpcc/grpc_client.go
Have the client check the mutation before submitting it.
Should submit #498 first.
Closes #494.
=> Check Mutations Locally in Client

cmd/keytransparency-server/frontend.go
In prod, this line can be replaced with a trillian/ecosystem/proxy
=> Start a Trillian Log Server inside the front end.

core/crypto/keymaster/verifier.go, core/crypto/signatures/factory/factory.go
=> Expose RSA Signatures

cmd/keytransparency-server/frontend.go
google/trillian#438 converted extension.Registry
to a simple struct. This PR makes the same change in
Key Transparency's main functions.
Fixes #517
=> Follow Trillian's registry conversion

docs/http_apis.md
The PUT request was out of date.
Updated it with a prototypical request.
=> Update HTTP docs

docs/http_apis.md, impl/sql/commitments/sql.go, impl/sql/mutations/mutations_test.go
This includes:
* Typo fix.
* Remove unused code.
* Unexport internal test function.
=> Minor fixes

cmd/keytransparency-server/frontend.go
Remove build breakage by proxying the Trillian log API to trillian binaries rather than running trillian inside the front end process.
=> Remove Trillian server from frontend

cmd/keytransparency-client/cmd/keys.go, cmd/keytransparency-client/cmd/root.go, core/client/ctlog/client_ct.go, core/vrf/p256/p256_test.go, impl/etcd/queue/etcd.go, impl/sql/sequenced/sequenced.go
This is the first part, as requested in #537.
=> Follow gosimple suggestions

core/mapserver/mapserver_test.go
Run `make fmt` on the entire repository.
=> Run make fmt

core/appender/appender.go, core/appender/trillian.go, core/appender/trillian_test.go, impl/config/config.go, impl/sql/sequenced/sequenced.go, integration/fake/fake_trilian_log.go
- Appender Local and Remote interfaces
- Create Trillian Client
- Fake
- Create LogClient helper
=> Create Trillian Interfaces

core/mutator/mutator.go, core/signer/signer.go, impl/sql/mutations/mutations.go, impl/sql/mutations/mutations_test.go
Closes #553.
See the bug for more context.
=> Change mutator.Mutation Read APIs to Return ( ] Range

.travis.yml, Makefile, coverage.sh
Uploads coverage analysis to https://codecov.io/gh/google/keytransparency
Example:
https://github.com/codecov/example-go
=> Add coverage testing to travis

core/signer/signer.go
Fix some minor errors after running `make presubmit`.
=> Fix presubmit errors

cmd/keytransparency-server/frontend.go, cmd/keytransparency-signer/backend.go
The time has come! This PR connects Key Transparency to the Trillian Map
Server. The next thing to do is to manually setup Key Transparency in a
proper cluster config and see how the performance numbers change.
Closes #573
=> Connect to Trillian Map

core/keyserver/keyserver.go
Previously, the keyserver would return "Permission Denied" when an auth header was missing.  Now it returns "Unauthenticated". 
cc @AMarcedone
=> Better auth error codes

cmd/keytransparency-client/cmd/root.go, cmd/keytransparency-signer/backend.go, core/authentication/fake.go, core/client/kt/requests.go, core/keyserver/keyserver.go, core/signer/signer_test.go, impl/config/config.go
Various spelling and formatting improvements to pass go vet.
=> Cleanup master

.travis.yml, coverage.sh
This PR reduces build times from 30 min to 2 minutes. 
https://scribu.github.io/travis-stats/#google/keytransparency/master
=> Use gnu parallel for faster tests

.keytransparency.yaml
Update reference to the trillian log server's public key.
Correct typo in map-id parameter name.
=> Update client config file .keytransparency.yaml

.travis.yml
=> Force python 2.7, source the gcloud path

.travis.yml
Resolves #632 (tested here: https://travis-ci.org/Liamsi/travis-kubernets-gcloud-test/builds/245320574)
=> Fix order of gcloud commands (tested)

.travis.yml
=> Add trillian dependencies to build step

README.md, scripts/deploy.sh
in the deploy script/README
resolves #636
=> Add new flag `--hash_strategy=TEST_MAP_HASHER` to the create tree cmd

.travis.yml
=> Fix travis before_deploy step: docker-ce replaces docker-engine (#642)

scripts/prepare_server.sh
=> Fixes (non-critical) syntax error in prepare_server.sh

core/proto/keytransparency_v1_types/keytransparency_v1_types.proto
Some typos I stumbled upon while reading through proto files.
resolves #652
=> Fix some typos

.keytransparency.yaml, deploy/kubernetes/keytransparency-deployment.yml.tmpl, scripts/prepare_client.sh
Also, make `MIN_SIGN_PERIOD` and `MAX_SIGN_PERIOD` explicit in the kubernetes conf
resolves #621
also resolves #658 (log key not found)
=> Autom. expose ports and an external IP for kt-server and Prometheus

.travis.yml, Makefile, scripts/travis-presubmit.sh
This PR forces travis to fail if any of the following has issues:
- `gofmt`.
- `golint`.
- `go vet`.
- `errcheck`.
- `gocyclo`.
- `ineffassign`.
- `misspell`.
- Missing license somewhere.
Closes #682.
=> Enhance Travis Presubmit Process

deploy/kubernetes/keytransparency-deployment.yml.tmpl, docker-compose.yml
Rename vars in the docker-compose.yml according to kt-server Dockerfile:
remove CERT (called TLS_CRT_PATH now)
make paths to keys explicit in kubernetes config
resolves #692
=> Update docker-compose / kubernetes config

scripts/configure_trillian.sh, scripts/log_payload.json
- use correct `hash_strategy` and `hash_algorithm`
- return HTTP error code on failure
=> Fix hasher and return curl's HTTP status code

deploy/kubernetes/trillian-deployment.yml
This fixes our deploy step. Part of #712.
/cc @AMarcedone
=> Fix kt's trillian kubernetes config to catch up with trillian#667

docker-compose.yml
Rename signer with sequencer and fix typo
=> fix docker-compose

core/client/gobindclient/client.go
=> Fix client API typo #794

cmd/keytransparency-monitor/main.go, cmd/keytransparency-sequencer/main.go, cmd/keytransparency-server/main.go, cmd/serverutil/serverutil.go
Gather common server functions into a utility package.
Currently this package contains one function, but it will grow over
time as we develop a common framework for server setup.
=> Refactor: serverutil package

core/client/gobindclient/client.go, core/client/multi/writer.go, core/monitor/storage/storage.go, core/mutator/entry/mutator.go
More upstream Go readability code cleanup
=> Readability code cleanup

cmd/keytransparency-monitor/main.go, cmd/keytransparency-sequencer/server.go, cmd/keytransparency-server/main.go, cmd/serverutil/serverutil.go
=> Refactor GrpcGatewayMux to common function

core/api/v1/keytransparency_proto/admin.proto, core/api/v1/keytransparency_proto/keytransparency.proto
Just fixing a few trailing whitespaces in comments that I noticed earlier.
=> trailing whitespace fixes

core/adminserver/admin_server_test.go, core/fake/trillian_log_client.go, impl/integration/env.go
This PR follows the API changes in google/trillian#951
=> Fix integration tests

cmd/keytransparency-sequencer/main.go, core/integration/alltests.go, core/sequencer/sequencer.go, impl/integration/env.go
- Reorganize the order of imports in the sequencer to match #920 
- Add a missing package comment
=> Consistency nits

cmd/keytransparency-client/cmd/hammer.go, cmd/keytransparency-client/cmd/keys.go, cmd/keytransparency-client/cmd/root.go, core/client/hammer/hammer.go
This PR allows hammer operations to be used in different contexts.
It also slightly simplifies the channel logic that was used in the hammer.
=> Refactor hammer as a library

cmd/gen-test-vectors/main.go, cmd/keytransparency-client/cmd/keys.go, core/integration/client_tests.go, core/mutator/entry/mutation.go, core/mutator/entry/mutator.go, core/testutil/tink.go, impl/sql/domain/storage_test.go
This PR follows general API cleanup in the Tink library:
google/tink#93
https://github.com/google/tink/commit/92c541b7a9a859032672a253e2b0edd83655b7f9
=> Follow Tink Upgrades

core/testutil/fakeserver.go
`127.0.0.1` doesn't work on IPv6 only hosts :-)
=> Use generic localhost

cmd/keytransparency-sequencer/main.go, core/sequencer/sequencer.go, impl/integration/env.go
Injects prometheus in the open source implementation, while
allowing for other monitoring implementations.
=> Use flexible implementations with metric factory

deploy/kubernetes/db-deployment.yaml, deploy/kubernetes/db-service.yaml, deploy/kubernetes/log-server-deployment.yaml, deploy/kubernetes/log-server-service.yaml, deploy/kubernetes/log-signer-deployment.yaml, deploy/kubernetes/log-signer-service.yaml, deploy/kubernetes/map-server-deployment.yaml, deploy/kubernetes/map-server-service.yaml, deploy/kubernetes/monitor-deployment.yaml, deploy/kubernetes/monitor-service.yaml, deploy/kubernetes/prometheus-deployment.yaml, deploy/kubernetes/prometheus-service.yaml, deploy/kubernetes/sequencer-deployment.yaml, deploy/kubernetes/sequencer-service.yaml, deploy/kubernetes/server-deployment.yaml, deploy/kubernetes/server-service.yaml, docker-compose.yml
Also propogates the --auth-type=insecure-fake flag from
the kubernetes config to the docker-compose config.
=> Regenerate kubernetes configs with kompose

cmd/keytransparency-client/cmd/root.go, cmd/keytransparency-monitor/main.go, core/client/gobindclient/client.go, gometalinter.json
Follows alecthomas/gometalinter#505
=> Rename gometalinter gas to gosec

core/adminserver/admin_server.go
The wrong number of arguments were being passed to Errorf.
=> Fix vet error

core/sequencer/server.go
Blocked on google/trillian#1300
Simplify the sequencer code by reusing a verifying map client.
=> Use MapClient's convenience methods

.travis.yml
Auto follow the latest go version
=> Bump travis go version

core/api/v1/keytransparency.proto
Updating comment to reference the correct field name.
=> Update the comment on EntryUpdate.committed field

core/keyserver/keyserver.go, core/keyserver/keyserver_test.go, core/keyserver/validate.go
Fixes #1101. Still needs integration tests, and should eventually use a batch API in Trillian for efficiency.
=> Implement ListUserRevisions

core/sequencer/server.go, core/sequencer/trillian_client.go
=> Write to Trillian Map At Revision

core/frontend/frontend.go
The frontend signs user updates on behalf of the provider.
=> Frontend implementation

.golangci.yml, cmd/keytransparency-monitor/main.go, core/client/client.go, core/client/get_and_verify.go, core/client/gobindclient/client.go, core/client/multi/writer.go, core/client/verify.go, core/crypto/vrf/p256/p256.go, core/integration/client_tests.go, core/keyserver/keyserver_test.go, core/keyserver/validate.go, impl/integration/env.go, impl/sql/directory/storage.go, impl/sql/mutationstorage/mutations.go
Turns on linting for the whole repo, not just fresh code. 
* Turn off noisy linters 
* Fix outstanding linter warnings
=> Fix linter backlog

core/adminserver/admin_server.go, core/adminserver/admin_server_test.go, core/testdata/directory.json, core/testdata/getentryresponse.json
Reverts google/keytransparency#1157
Trimmed too much. 
There is a bit of confusion over the importance of the hash algorithm and signing algorithm fields.
=> Revert "Trim Directory info"

.travis.yml
Fixes the following error:
`gometalinter: error: unknown linters: megacheck`
=> Use golangci-lint

core/adminserver/admin_server.go, core/adminserver/admin_server_test.go, core/testdata/directory.json, core/testdata/getentryresponse.json
Reverts google/keytransparency#1162
Only return fields that Key Transparency clients actually need for verification.
=> Trim Directory Tree Info

.travis.yml, cmd/keytransparency-client/cmd/get.go, cmd/keytransparency-client/cmd/hammer.go, cmd/keytransparency-client/cmd/history.go, cmd/keytransparency-client/cmd/keys.go, cmd/keytransparency-client/cmd/post.go, cmd/keytransparency-client/cmd/root.go, core/fake/domain_storage.go, core/integration/client_tests.go, core/monitor/verify.go
Cleanup unused parameters
Use lowercase variable names in parameters
Other nits
=> Bump the golangci-lint version to v1.13.1

cmd/keytransparency-sequencer/main.go, cmd/keytransparency-server/main.go, core/keyserver/keyserver.go, core/sequencer/sequencer.go, core/sequencer/server.go, core/sequencer/trillian_client.go, impl/integration/env.go
Thanks to @Zyqsempai for making this possible in #1167
=> Remove unused Trillian Admin connections

cmd/keytransparency-sequencer/main.go, core/sequencer/sequencer.go
Support controlling the directories a binary sequences with a flag, rather than the entire set by default.
=> AddDirectoryForSequencing

impl/authorization/interceptor.go
=> Typo "hander" should be "handler"

.golangci.yml, .travis.yml, README.md, cmd/gen-test-vectors/main.go, core/client/multi/writer.go, core/crypto/tinkio/pem.go, core/crypto/tinkio/protofile.go
* Bump linter version to 1.13.2
* Add checks for improper imports
* Trim exception list
=> Linter fixups

docker-compose.override.yml, docker-compose.yml
Moved expose mysql port to override compose file
Related PR: https://github.com/google/keytransparency/pull/1201
=> Move mysql expose port to override compose file

cmd/keytransparency-client/cmd/hammer.go, cmd/keytransparency-client/cmd/keys.go, cmd/keytransparency-client/cmd/post.go, core/client/hammer/hammer.go, core/crypto/tinkio/pem.go, core/fake/usermanager.go, core/mutator/entry/mutation.go, core/mutator/entry/mutation_test.go, core/mutator/entry/mutator.go, core/testutil/tink.go, impl/sql/keysets/keysets.go, impl/sql/keysets/keysets_test.go
=> Follow tink updates

core/sequencer/server.go
* Add logid to the sequencer read metric.
=> Add logid to read metric

core/mutator/entry/entry.go, core/mutator/entry/entry_test.go, core/mutator/entry/mutator.go, core/mutator/mutator.go, core/sequencer/mapper/fns.go, core/sequencer/runner/native.go, core/sequencer/runner/native_test.go
=> Make the reduceFn associative

core/integration/client_tests.go
=> Reduce batch_size and timeouts

core/sequencer/server.go
The error metric has two dimensions but we were only setting one of them.
=> Fix error metric

core/sequencer/sequencer_api.proto
Remove trailing whitespace in sequencer_api.proto
=> Remove trailing whitespace in sequencer_api.proto

cmd/keytransparency-sequencer/main.go, core/sequencer/sequencer.go
This will let us have the ability to change it on the fly.
=> Move Sequencer batchSize out of constructor

core/monitor/verify.go
Fix the build. Follow the changes introduced in google/trillian#1507
=> Follow google/trillian#1507

core/keyserver/keyserver.go
Many codes.Canceled errors are being converted into codes.Internal.
As a result, monitoring is getting overly excited.
Solution: keep the original error codes.
=> Pass through grpc error codes

core/keyserver/keyserver.go
=> Don't drop errors other than NotFound

core/keyserver/keyserver.go
Added logging for all errors returned by:
GetUser
BatchGetUser
BatchGetUserIndex
=> Add top level logging for Get User RPCs

core/integration/client_tests.go
Update tests to periodically write log root revisions
=> Update tests to periodically write log root revisions

core/keyserver/keyserver.go
Add new metric to count revisions written to the sequencer queue.
=> Add new metric to count revisions written to the queue

core/monitor/verify.go
=> Use pointers to HStar2LeafHash

core/keyserver/keyserver.go, core/keyserver/keyserver_test.go
NewFromWrappedKey hides an RPC to a key material server.
This should not be called for every VRF evaluation.
=> Move NewFromWrappedKey up a layer

core/sequencer/runner/native.go, core/sequencer/runner/native_test.go, core/sequencer/server.go
Create a worker pool for running reduce functions
=> Parallize JoinAndReduce in ApplyRevision

core/sequencer/sequencer.go
Factor out ForAllMasterships so it can be used for other functions
=> Refactor ForAllMasterships

core/sequencer/server.go, core/sequencer/server_test.go
Towards github.com/google/trillian#1738.
=> Fix proto copying in server_test.

impl/integration/main_test.go
Makes the code easier to read and maintain.
=> Remove unnessesary func()

core/testdata/transcript_go_proto/transcript.proto
=> Remove trailing whitespace

.travis.yml, cmd/keytransparency-monitor/Dockerfile, cmd/keytransparency-sequencer/Dockerfile, cmd/keytransparency-server/Dockerfile, go.mod, go.sum
Improve the reliability of `go mod download` in the docker builds.
=> Turn on GOPROXY

.travis.yml
This speeds up the build
Isolates installs build specific stages
Speeds up error identification to specific stages
Depends on #1330
=> Use Travis Build Stages

.travis.yml, core/client/batch_get_and_verify.go, core/keyserver/keyserver.go, go.mod, go.sum
This PR both adds race tests, and fixes a few outstanding race conditions. 
Blocked on #1336 -- Fixing some problem with GOPROXY
=> Check for data races in travis

go.mod, go.sum
Also fixes a go.sum missmatch with uber/prototool
=> gotip mod tidy

cmd/keytransparency-sequencer/main.go
This PR puts the directory detection into its own task with an independent cadence.
=> Run directory detection independently

impl/integration/env.go
Don't close the db before using it
=> Close db after environment is closed

.travis.yml
=> Enable integration tests in travis

.golangci.yml
Set golangci-lint version explicitly
=> Fix golangci-lint.com integration

core/sequencer/server.go, core/sequencer/server_test.go
Pagination should not be modifying the continuation tokens. 
They are dangerous and not for consumption.
=> Do pagination the right way

core/keyserver/keyserver.go, core/sequencer/server.go
This preserves existing behavior while it is being fixed.
=> Report watermarks in microseconds

go.mod, go.sum
https://github.com/google/tink/releases/tag/v1.3.0-rc3
```
go get github.com/google/tink/...@v1.3.0-rc3
```
=> Upgrade tink to v1.3.0-rc3

.travis.yml, deploy/docker/init/Dockerfile, docker-compose.override.yml, docker-compose.prod.yml, docker-compose.yml, scripts/docker-compose_test.sh, scripts/docker-stack-wait.sh
Use `docker swarm` 
Docker swarm supports running service on multiple nodes and is a closer match to k8. 
Docker swarm also supports load balancers which is what we will be using for TLS termination in the future.
=> Use Docker Swarm

scripts/deploy.sh
The previous date command used the mac format
=> Use linux date command format

README.md
Fixes #1207 - Explain directories
=> Explain directories

README.md
=> Use a real public key in the example

internal/backoff/backoff.go
Preserve error details when indicating that an error should
be retried.
=> Use error wrapping in backoff

core/sequencer/election/tracker_test.go
Use the metric factor that's purpose specific for tests
=> Use inert metric factory

go.mod, impl/spanner/database.go, impl/spanner/database_test.go, impl/spanner/ddl_test.go, impl/spanner/keytransparency.ddl
Supports a delayed connection to the spanner database.
=> CloudSpanner database opener object

.github/workflows/build.yml
* Also run the build action on pull requests
=> Use Go 1.14 in github actions

core/integration/storagetest/mutation_logs.go, core/integration/storagetest/mutation_logs_reader.go, core/keyserver/keyserver.go, core/keyserver/revisions_test.go, core/sequencer/server_test.go, impl/memory/mutation_logs.go, impl/mysql/mutationstorage/mutation_logs.go, impl/mysql/mutationstorage/mutation_logs_test.go, impl/spanner/mutations/table.go, impl/spanner/mutations/table_test.go
Clarify that updates are processed in "batches"
=> Rename Send to SendBatch

docs/design.md
Even though this is an older design doc, I still thought others might appreciate having the right proto link.
=> Fix a broken link and grammar in design.md

core/client/hammer/hammer.go
This kind of hammer operation creates mutations assuming the users are 'new',
thereby skipping a read first, lessening the load on the server during write
load tests.
=> Create user hammer op

core/sequencer/trillian_client.go, go.mod, go.sum
Helps free up dead spanner sessions
=> Add timeouts to outgoing map read rpcs

core/client/MeetInTheMiddle.md, core/client/meetinthemiddle.go, core/client/meetinthemiddle_test.go, docs/design_new.md, docs/meet-in-the-middle.md
=> Meet in the middle algorithm
