docs/design.md

Changing `an` to `a` seems correct, but I took a guess at what the next bit should have been.

Typo fix in documentation

---

docs/design.md

Currently 404. This PR fixes the link in design.md to the protocol buffers spec for the service.

Fix protobuf link in design.md.

---

.travis.yml
vendor/vendor.json

go get -u google/key-transparency results in a build break.
go-grpc upgraded to grpc.SupportPackageIsVersion4
This PR updates the generated files to match.

regenerate generated files with protoc 3.1.0

---

.travis.yml

Now that google/certificate-transparency#1362 is merged, we no longer have a dependency on OpenSSL.  Remove this from the build file. 
Closes #465

Remove ssl from build

---

cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-signer/backend.go
core/crypto/keymaster/interface.go
core/crypto/keymaster/keymaster.go
core/crypto/keymaster/signer.go
core/crypto/keymaster/signer_test.go
core/crypto/keymaster/verifier.go
core/crypto/keymaster/verifier_test.go
core/crypto/signatures/factory/factory.go
core/crypto/signatures/interface.go
core/crypto/signatures/p256/ecdsa_p256.go
core/crypto/signatures/p256/ecdsa_p256_test.go
core/crypto/signatures/rsa/rsa_sha256_3072.go
core/crypto/signatures/rsa/rsa_sha256_3072_test.go
core/mutator/entry/entry.go
core/mutator/entry/entry_test.go
integration/client_test.go
integration/testutil.go

Establishes a 1:1 relationship between the signer and
DigitallySigned.
Keymaster operations on groups of signers and verifiers are
in a separate package with a separate protobuf serialization.

Separate Signer from Keymaster operations

---

docs/architecture.md

Fix a typo in docs

---

README.md

Resolves Etcd membership discovery failures in new clusters.
https://github.com/coreos/etcd/blob/master/NEWS

Bump Etcd dependency to v3.1.3 (Current release)

---

impl/proto/keytransparency_v1_service/gen.go
impl/proto/keytransparency_v1_service/keytransparency_v1_service.pb.go

The gRPC ecosystem project updated it's generators to reference
the standard googleapi paths in grpc-ecosystem/grpc-gateway#325
This PR makes the same changes in this repo to follow the standard.

Update GoogleAPI import path

---

cmd/keytransparency-signer/backend.go
core/keyserver/keyserver_test.go
core/mutator/mutator.go
core/signer/signer.go
core/tree/tree.go
impl/sql/mutations/mutations.go
impl/sql/mutations/mutations_test.go
impl/sql/sqlhist/sqlhist.go
impl/sql/sqlhist/sqlhist_test.go
integration/testutil.go

This PR stores mutations in the local database after being processed by the queue/signer. It also stop sending mutations to a CT log.
Partial #507.

Store Mutations in Local Database

---

README.md

Now that Certificate Transparency's Go no longer uses cgo
we can remove the apt-get install build-essential lines from
the readme.

Remove C++ install instructions from README

---

core/sequenced/sequenced.go
impl/sql/sequenced/sequenced.go
impl/sql/sequenced/sequenced_test.go

Creates a place for storing generic items that have been sequenced.
Particuarly of the form: mapID, epoch.
Technically, a Trillian Log could serve the same purpose, but...
- You can't do an atomic transaction across an API call.
- We need to separate storing signed map heads from putting them in
an append only log in order to match the trillian Map API.
This API supports the trillian Map function for storing Signed Map Heads.

Create a Sequenced table

---

core/keyserver/keyserver.go
core/keyserver/keyserver_test.go
core/tree/tree.go
impl/sql/sqlhist/sqlhist.go
impl/sql/sqlhist/sqlhist_test.go

This simplifies reading both leaves and their neighbors within the same
transaction.
Contributes to #530

Use transaction.Txn for NeighborsAt

---

.travis.yml

Update Go version in Travis to 1.8.
This fixes and error seen in this build:
https://travis-ci.org/google/keytransparency/builds/216732454

Update Go Version in Travis

---

core/crypto/signatures/p256/ecdsa_p256_test.go
core/keyserver/keyserver.go

This PR fixes `make presubmit` errors after updating the presubmit tools: `golint`, `errcheck`, `gocyclo`, `ineffassign`, and `misspell`.
The following is the only outstanding error left. A fix is already included in #524.
```
./impl/sql/mutations/mutations_test.go:38:1: context.Context should be the first parameter of a function
```

Fix Presubmit Errors

---

core/admin/interface.go
core/admin/static.go
core/admin/static_test.go
integration/fake/fake_trilian_log.go

Support multiple backend logs by storing their configuration
in an in-memory table.
In the future, the Add* commands of the Admin interface will perform
the needed setup such as inserting master rows in the various
sub-components.
Further in the future, this in-memory table will be backed by a database
rather than configured in-memory from the commandline.
#534

Multi-tenant configuration support

---

integration/fake/fake_trilian_log.go

- Return an internface for the fake rather than the object
- Make the object private
- VerifyInclusion
- VerifyInclusionAtIndex

Add methods to fake.logClient

---

core/mapserver/mapserver.go
core/mapserver/mapserver_test.go
integration/fake/fake_trilian_log.go

This begins the migration to trillian Maps by separating the internal bits of Key Transparency which implement the same functions.
This adds `mapserver` which implements `trillian.MapServerClient` using `tree.Sparse` and several other internal KT modules. 
The next PR will convert the signer to use `mapserver`
#486 #172

Create trillian.MapServer inside Key Transparency

---

core/authentication/fake.go
core/authentication/fake_test.go
core/mapserver/mapserver.go
impl/google/authentication/google.go

NewContext and FromContext have been deprecated in favor of
NewIncomingContext NewOutgoingContext and
FromIncomingContext and FromOutgoingContext.
This follows google/grpc-go#1157

Update grpc metadata API

---

cmd/keytransparency-server/frontend.go
cmd/keytransparency-signer/backend.go
core/keyserver/keyserver_test.go
core/mapserver/mapserver.go
core/mapserver/mapserver_test.go
core/signer/signer.go
core/tree/tree.go
impl/etcd/queue/etcd.go
impl/sql/sqlhist/sqlhist.go
impl/sql/sqlhist/sqlhist_test.go
impl/transaction/txn.go
integration/client_test.go
integration/testutil.go

Some integration tests make GET requests while new epochs are being created in the background, using the same *sql.DB connection, producing a transient "database is locked" error. 
Background: 
- Reading while a write is occurring requires multiple *sql.DB connections to the same db. 
- In-memory tests only allow one *sql.DB connection to the test database.
- *sql.DB is [not threadsafe](https://github.com/mattn/go-sqlite3#faq) for write/reads on multiple goroutines.
Solution: 
Synchronize access to sql.DB by waiting for epoch creation to finish before making GET requests.  
It adds a channel for new epoch notifications which allows tests to wait for new epochs before advancing to the next steps in the test. 
This PR resolves this issue by
- Converting all `sqlhist` operations to …

Fix DB locked flakiness in tests

---

.travis.yml
Makefile

Travis is failing when running coverage. Coverage is not adding any benefits in Travis so this PR removes it. We still have coverage when running presubmit locally.

Create Travis presubmit make rule without coverage

---

cmd/keytransparency-server/frontend.go
cmd/keytransparency-signer/backend.go
core/keyserver/keyserver.go
core/keyserver/keyserver_test.go
core/mapserver/mapserver.go
core/signer/signer.go
core/transaction/txn.go
core/tree/sparse/verifier/verifier_test.go
impl/sql/mutations/mutations_test.go
impl/sql/sequenced/sequenced_test.go
impl/sql/sqlhist/sqlhist.go
impl/sql/sqlhist/sqlhist_test.go
impl/sql/testutil/testutil.go
impl/transaction/txn.go
impl/transaction/txn_test.go
integration/testutil.go

This PR removes etcd dependency from the transaction object. Now, this object is simply a wrapper around SQL transaction. We still need it though to support multiple simultaneous database backend.
Closes #522.

Remove etcd Dependency from the Transaction Object

---

cmd/keytransparency-client/grpcc/grpc_client.go
cmd/keytransparency-server/frontend.go
cmd/keytransparency-signer/backend.go
core/client/kt/verify.go
core/keyserver/keyserver.go
core/keyserver/keyserver_test.go
core/mapserver/mapserver.go
core/mapserver/mapserver_test.go
core/mapserver/readonly.go
core/signer/signer.go
integration/client_test.go
integration/testutil.go

Use an internal implementation of the trillian map server. 
In the keyserver:
- Use GetLeaves to retrieve leaf values and inclusion proofs.
- Use GetSignedMapRoot to retrieve the current epoch.  (Replaces sths object)
In the signer:
- Collect all mutations that have occurred since the last epoch.
- GetLeaves for the respective indexes
- Verify and Apply the mutations.
- Call SetLeaves to create a new epoch with the new values. 
TODO:
- Pass an expected epoch field to make sure that the read/write cycle to the mapserver is atomic. google/trillian#559
- Use mastership election to make sure that only one signer is active at any point. #565
Contributes to #486

Use mapserver in signer

---

core/mapserver/mapserver.go
core/mapserver/mapserver_test.go
core/mapserver/readonly.go

After adding `GetSignedMapRootByRevision` to Trillian and running `go get -u ./...` in Key Transparency, some breakages needed to be fixed.

Fix broken build after Trillian update

---

core/keyserver/keyserver_test.go
core/mutator/mutator.go
impl/sql/mutations/mutations.go
impl/sql/mutations/mutations_test.go

This allows callers to specify both count and end sequence in mutations `ReadRange` API. The returned range stops when either count or end sequence is reached, whichever comes first.
Partial #59.

Add End Sequence to ReadRange API

---

core/crypto/dev/dev.go
core/crypto/dev/dev_test.go
core/crypto/keymaster/signer_test.go
core/crypto/keymaster/verifier_test.go
core/crypto/signatures/p256/ecdsa_p256_test.go
core/mutator/entry/entry_test.go
integration/client_test.go
integration/testutil.go

Some cryptographic tests need a repeatable source of randomness to
make tests repeatable and test vectors meaningful. Multiple tests
had a DevZero object. Rather than repeating this object over and over,
it makes sense to have one, tested version of it.

Create a dev package to hold dev.Zero

---

core/crypto/commitments/commitments.go
core/crypto/commitments/commitments_test.go
core/crypto/dev/dev.go
core/crypto/dev/dev_test.go
core/crypto/keymaster/signer_test.go
core/crypto/keymaster/verifier_test.go
core/crypto/signatures/p256/ecdsa_p256_test.go
core/mutator/entry/entry_test.go
integration/client_test.go
integration/testutil.go

Merge #595 first
Add a modifiable source of randomness to facilitate reliable tests.
Uses the new dev.Zero reader to generate test vectors.

Add test vectors to crypto/commitment

---

README.md
cmd/keytransparency-client/cmd/post.go

New commandline format:
./keytransparency-client post user@domain.com app1 -d dGVzdA==
--config=./.keytransparency.yaml
Fixes #606

Update keytransparency-client documentation

---

cmd/keytransparency-client/cmd/post.go
cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-server/frontend.go
core/authentication/fake.go
core/authentication/fake_test.go
core/keyserver/validate_test.go
integration/client_test.go
integration/testutil.go

Adds support for fake authentication both to the client and the server (to be used for debug only). 
This allows the client to authenticate as user@domain.com by passing the additional parameter
`--fake-auth-userid=user@domain.com `
to the keytransparency-client binary (rather than having to get an actual oauth token). 
The feature should be enabled on the server side by starting the keytransparency-server binary with the ` --insecure-fake-auth ` flag.

Add support for fake authentication

---

core/crypto/vrf/p256/p256_test.go

I found this bug while working on the JavaScript client.

Bug fix: replace impossible "&&" with "||" in VRF test.

---

.travis.yml

Replace `tar -xzf service_key.tar.gz` with `tar -xzf travis_secrets.tar.gz`
to make travis pass (hopefully): https://travis-ci.org/google/keytransparency/builds/244962734#L5015-L5022

Another place where the name of the credentials file should be adapted

---

.dockerignore
.travis.yml
scripts/deploy.sh

and move `gcloud auth` command from the deploy script to travis, delete secret_key after usage (so it doesn't end up in docker images)
resolves #623

Add .dockerignore file

---

.travis.yml
scripts/deploy.sh

See if `gcloud --quiet components update kubectl` works properly now that we `source $HOME/google-cloud-sdk/path.bash.inc`
Also, move all gcloud initialization to travis.yml.
resolves #630 (hopefully)

Try gcloud update components kubectl without sudo

---

README.md
scripts/deploy.sh

only MAP-type trees can use new hash-strategy: `TEST_MAP_HASHER` (see google/trillian#685)
resolves #638

LOG still uses RFC_6962

---

core/crypto/vrf/p256/p256.go
core/crypto/vrf/p256/p256_test.go

VRF uniqueness could be violated because the VRF output itself was not
included in the the computation of `s`, the commitment to the VRF and
zero knowledge proof. Fixes #567. 
Other changes also included in this PR: 
- H2(.., m, ..) -> H2(.., H1(m),..) for better alignment with the NSEC5 VRF (sec 3.5).  This change was suggested by Leonid Reyzin and approved by @jcb82 (the CONIKS paper has been updated).
- Variable name notation has been updated for better code clarity. 
- Add test vectors #613 
References:
- [NSEC5 Paper](https://eprint.iacr.org/2017/099.pdf)
- [CONIKS Papser](https://eprint.iacr.org/2014/1004.pdf)

Ensure VRF uniqueness

---

.keytransparency.yaml
README.md
cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-server/Dockerfile
docker-compose.yml
impl/google/authentication/google.go
scripts/deploy.sh
scripts/prepare_client.sh
scripts/prepare_server.sh

Use a default http client to query https://www.googleapis.com/oauth2/v2
Also, use environment vars for `LOG_ID` and `MAP_ID` in the `docker-compose.yml` file (makes local testing/debugging a easier/more convenient).
Resolves #640 
Resolves #617

Remove service-key requirement from kt-server

---

README.md
cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-signer/main.go
docker-compose.yml
impl/config/config.go
scripts/configure_trillian.sh
scripts/deploy.sh

Use HTTP POST to create trees, store the public keys and export `LOG_ID` and `MAP_ID` vars.

Create tree scripts

---

core/appender/trillian.go
core/keyserver/keyserver.go

Our first SignedMapRoot starts at revision 1
(Revision 0 is completely empty).
Log leaves, however, start at 0.
Fixes #654

Fix off by one error between Map and Log

---

cmd/keytransparency-client/grpcc/grpc_client.go
core/keyserver/keyserver.go
core/mutator/entry/entry.go
core/mutator/entry/entry_test.go
core/mutator/mutator.go
core/proto/keytransparency_v1_types/keytransparency_v1_types.proto

and prevent calling `Mutate(...)` without checking that the mutation is actually valid:
- remove `mutation.CheckMutation` from interface 
- `mutation.Mutate` does both now: checks the mutation and returns the update (which it created anyway)

Simplify mutator interface: reduce code redundancy 

---

core/mutation/mutation_test.go
core/signer/signer_test.go

Add missing license headers in `core/mutation/mutation_test.go` and `core/signer/signer_test.go`.
Partial #682.

Add missing license

---

cmd/keytransparency-server/Dockerfile
cmd/keytransparency-signer/Dockerfile
docker-compose.yml

Changes the build context for the kt-server and the kt-signer to:
`$GOPATH/src/github.com/google/`
and uses the local trillian repo instead of fetching it (via go get)
resolves #689

Use local trillian repo when building Docker images 

---

cmd/keytransparency-signer/main.go
impl/config/config.go
scripts/log_payload.json

We currently create the tree using [log_payload.json](https://github.com/google/keytransparency/blob/a7b3f6246ec0be578713fca451afe260dce45317/scripts/log_payload.json#L8) which uses SHA256 as a hasher. The log-client created by the kt-signer used `OBJECT_RFC6962_SHA256`. A following PR should make this a param to `config.LogClient` and autom. read it (either from the json or from a cmd-flag/config flag).
Fixes `WaitForInclusion` timing out.
Together with google/trillian#729 this resolves #688

Use same hasher for LogClient and trillian-log

---

core/mutation/mutation.go

Fix panic'ing when accessing mutations API

---

core/mutation/mutation.go
deploy/kubernetes/keytransparency-deployment.yml.tmpl

Catch up with one off fix in mutations API
also fixes current kubernetes deployment (correct `VRF_PRIV`environment variable)
related to https://github.com/google/keytransparency/pull/661 and https://github.com/google/keytransparency/issues/654

Fix one-off error in mutations API

---

scripts/travis-presubmit.sh

Currently `golint` is not enforced in `scripts/travis-presubmit.sh`. This PR enforces it in order to detect style violations during Travis run.

Enforce golint in travis-presubmit.sh

---

cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-client/grpcc/grpc_client.go
core/client/kt/verify.go
core/tree/sparse/verifier/verifier.go
core/tree/sparse/verifier/verifier_test.go
integration/testutil.go
scripts/prepare_client.sh

MapID is part of SignedMapRoot and part of leaf and empty hash
computation. We can remove a bit of state from the client without a
reduction in security by relying on the value as reported by the server.

Use MapID as reported in SignedMapRoot

---

cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-client/grpcc/grpc_client.go
cmd/keytransparency-server/main.go
cmd/keytransparency-signer/main.go
core/client/kt/verify_test.go
core/crypto/vrf/p256/p256.go
core/signer/signer.go
impl/sql/mutations/mysql.go
impl/sql/mutations/sqlite.go
metalinter.json

Based on #732 
This PR turns on the following linter checks along with simple code fixups. 
- deadcode
- varcheck detects unused global variables
- interfacer - not turned on due to larger code changes needed, but did implement a fixup
- megacheck - detects use of deprecated interfaces. 
- gas - security checks

Turn on more presubmit checks

---

metalinter.json

Now that gometalinter doesn't panic on custom linters, we can enable the license check.
https://github.com/alecthomas/gometalinter/pull/333

Add license check

---

cmd/keytransparency-client/grpcc/grpc_client.go
core/client/kt/verify.go
integration/testutil.go
scripts/map_payload.json

The moment of truth! - Where we finally switch back to using the CONIKS
hashing algorithm successfully :-)
related to google/trillian#780

Use the CONIKS hasher

---

cmd/keytransparency-client/cmd/history.go
cmd/keytransparency-client/grpcc/grpc_client.go
core/fake/trillian_log_client.go
core/keyserver/keyserver.go
core/keyserver/validate.go
core/signer/signer.go
integration/testutil.go

Cleans up a few off by on errors and poor stopping condition logic in the list history command.
Fixes #756 
Rebased on #760 and #762. Merge them first.

Fix/756 Fix ListHistory command

---

deploy/kubernetes/keytransparency-deployment.yml.tmpl

Fixes typo in the kubernetes config: s/0.0.0.0.:8080/0.0.0.0:8080

Fix typo in kube config

---

Makefile
cmd/keytransparency-client/grpcc/grpc_client.go
core/client/kt/requests.go
core/mutator/entry/entry.go
core/mutator/entry/entry_test.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go
core/mutator/entry/mutator.go
core/mutator/entry/mutator_test.go
core/mutator/mutator.go

Previously the client code had a giant function for creating mutations. 
I realized that the process of creating a mutation is closely related to verifying a mutation. 
This PR creates
- A mutation creator `entry.Mutation`
- A mutation verifier / function`entry.Mutator`  Which verifies and applies a mutation to a previous entry in the tree. 
#588

Create a mutation manipulation object / API

---

CONTRIBUTORS
cmd/keytransparency-monitor/main.go
core/client/kt/verify.go
core/monitor/monitor.go
core/monitor/verify.go
core/mutation/mutation.go
impl/monitor/client/client.go
integration/monitor_test.go
integration/testutil.go

This PR contains the monitor verification logic which should be plugged into the monitor after #776  is merged.
Includes a fix for https://github.com/google/keytransparency/issues/800 and related to this a temporary workaround for #811. 
resolves #800

Monitor verification logic

---

README.md

Point to the Trillian MySQL setup instructions as a prerequisit for
using the Key Transparency unit tests.
Fixes #791

Document MySQL testing dependency

---

.travis.yml

It looks like python2 on travis is outdated.  This tries upgrading to python3 as the solution. 
sudo for pip-install is also required. 
```
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
SNIMissingWarning
```

Upgrade to python3 for docker-compose

---

core/crypto/signatures/p256/ecdsa_p256_test.go
core/crypto/signatures/rsa/rsa_sha256_3072_test.go
core/mutation/mutation_test.go
core/mutator/entry/entry_test.go

reflection.DeepEqual is not a reliable equality test for protos.
Use proto.Equal for protos as appropriate.

Use proto.Equal rather than reflection.DeepEqual

---

cmd/keytransparency-client/cmd/root.go

This PR removes the unused viper remote configuration feature.
The remote configuration feature was pulling in a whole dependency graph
that includes an unvenored etcd client which has the tendency of
breaking periodically.

Remove etcd dependency

---

core/crypto/vrf/p256/p256.go
core/crypto/vrf/p256/p256_test.go

Trillian supports opaque private key objects which can then be converted
back into private keys by `keys.NewSigner`.  Since VRF requires a
specific key type (ecdsa), not just a `crypto.Signer`, I've added a function to
perform the appropriate checks and type converstion.

VRF: NewFromWrappedKey

---

cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-server/main.go
core/client/grpcc/grpc_client.go
core/client/kt/requests.go
core/keyserver/keyserver.go
integration/testutil.go

Rather than passing a single logID, mapID, and vrf key to the keyserver, this PR now passes a reference to `adminstorage`, where each of these items can be looked up based on the domainID in the incoming gRPC request. 
This PR also makes the first adjustments to the integration tests to start using the admin API.  
Further PRs will complete the process as we add domainID support to other modules. 
This PR makes a cosmetic change:  Edited files will show a move toward using `pb` and `gpb` as the renamed imports for protos and service protos. 
#534

Add domainID to keyserver 

---

core/client/gobindclient/client.go
core/crypto/signatures/p256/ecdsa_p256.go
core/mutator/entry/mutation.go
core/mutator/entry/mutator.go
core/mutator/entry/mutator_test.go
vendor/github.com/benlaurie/objecthash/go/objecthash/objecthash.go

API changes require:
* client code to CommonJSONify structs, protobufs, etc. before calling
objecthash.ObjectHash();
* client code to handle error returns (earlier objecthash would panic).

Update vendored objecthash to e06914f

---

.travis.yml
Makefile
cmd/keytransparency-client/cmd/root.go
cmd/keytransparency-monitor/main.go
core/client/gobindclient/client.go
gometalinter.json
integration/testutil.go

The [Go AST Scanner](https://github.com/GoASTScanner/gas) was [recently](https://github.com/alecthomas/gometalinter/commit/3e602d9013785a8e54137caf409564a966586b85) fixed. This PR makes the needed corrections in this repo.
As a result, the mac firewall will no longer complain when running integration tests!

Linter cleanup GoMetaLinter:gas

---

core/client/kt/requests.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go

This separates the process of creating a mutation for a user
from setting the previous value of entry. We may want to
set the previous entry separately in some cases.

Mutation.SetPrevious

---

core/client/kt/requests.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go

This removes the need for callers to set the domainID in the request before sending

Add domainID to mutation

---

core/fake/trillian_map_client.go
core/mutationserver/mutation_test.go

Also moves the fake TrillianMapClient into core/fake
and cleans up the test to use a proper client interface.

Add GetLeavesByRevision to fake.TrillianMapClient

---

core/fake/trillian_log_client.go
core/fake/trillian_map_client.go
core/mutationserver/mutation_test.go
integration/testutil.go

If the function signatures change, we get a compile time error.
We would, instead, like the error to occur at the point where
the object is used. At this point, an alternate object can be used
if nessesary.

Don't return raw grpc interfaces

---

core/keyserver/keyserver.go
core/mutationserver/mutation.go

Do this where a specific revision is required.
When retrieving the latest revision, GetLeaves is still used.
In a later trillian API change the special '-1' revision will
no longer be used.

Switch from GetLeaves to GetLeavesByRevision.

---

cmd/keytransparency-client/cmd/root.go
core/client/gobindclient/client.go
core/client/grpcc/grpc_client.go
integration/testutil.go

We were using a more general interface (grpc.Client) to the Key Transparency client than needed.

Use specific interface 

---

core/adminserver/admin_server.go
core/adminstorage/admin_storage.go
core/fake/admin_storage.go
core/keyserver/epochs_test.go
impl/sql/adminstorage/admin_storage.go
impl/sql/adminstorage/admin_storage_test.go

Use the adminstorage.Domain object to write directly rather than
giving each piece of the struct as a positional parameter. This makes
the function signature simpler, and eases code maintinance.

Cleaner adminstorage.Write function

---

cmd/keytransparency-sequencer/main.go
cmd/keytransparency-server/main.go
core/fake/mutation_storage.go
core/keyserver/epochs.go
core/keyserver/epochs_test.go
core/keyserver/keyserver.go
core/mutator/mutator.go
core/sequencer/sequencer.go
impl/sql/mutationstorage/mutations.go
impl/sql/mutationstorage/mutations_test.go
integration/testutil.go

Transactions are not currently serving any purpose.
There are no sequences of database calls that need to be coordinated
atomically.
The transaction abstraction was orginally created to support atomically
acking an item out of a queue and saving it.
1. The queue and the database can often be using different technologies
that make a single transaction between them not possible.
2. The specifics of the queue, databases, and other subsystems are
implementation details that should be handeled in impl/ rather than
creeping into the apis themselves.

Remove transactions from mutation api

---

core/fake/mutation_storage.go
core/keyserver/epochs.go
core/keyserver/epochs_test.go
core/mutator/mutator.go
core/sequencer/sequencer.go
impl/sql/mutationstorage/mutations.go
impl/sql/mutationstorage/mutations_test.go

Prevent a crazy number of mutations from going into a single epoch
and overloading the trillian map.
DiffBase #896

 Set a maximum batch size for sequencing

---

core/fake/mutation_storage.go
core/keyserver/epochs.go
core/mutator/mutator.go
core/sequencer/sequencer.go
impl/sql/mutationstorage/mutations.go
impl/sql/mutationstorage/mutations_test.go

This PR allows sequence numbers to be transmitted in the mutation objects themselves. 
This is in preparation for creating a proper queue who's `mutator.Mutation` objects can be properly dequeued and consumed by the sequencer without enforcing a strict ordering over mutations.

Send sequence numbers along with values in ReadBatch

---

core/adminserver/admin_server.go
core/domain/storage.go
core/fake/domain_storage.go
core/fake/mutation_storage.go
core/keyserver/epochs.go
core/keyserver/epochs_test.go
core/keyserver/keyserver.go
core/mutator/mutator.go
core/sequencer/sequencer.go
impl/sql/domain/storage.go
impl/sql/domain/storage_test.go
impl/sql/mutationstorage/mutations.go
impl/sql/mutationstorage/mutations_test.go
impl/sql/mutationstorage/mysql.go
impl/sql/mutationstorage/queue.go
impl/sql/mutationstorage/queue_test.go
impl/sql/mutationstorage/sqlite.go
integration/testutil.go

This PR switches the mutation storage table from using `mapID` as the primary mutation key and replaces it with `domainID`.  This achieves a slightly cleaner abstraction and brings internal and external APIs into alignment.

Index mutations by domainID

---

cmd/keytransparency-sequencer/main.go

`StartSequencingAll` was changed from a non-blocking function, to a blocking function that could return an error, per Go style.  This change should have been included in #862
Fixes #868

Launch StartSequencingAll in a separate goroutine

---

core/keyserver/keyserver.go

GetDomain was not filling out the DomainID field in the response.

Fix GetDomain

---

core/fake/trillian_log_client.go
core/fake/trillian_map_client.go
core/keyserver/epochs.go
core/keyserver/keyserver.go
core/keyserver/keyserver_test.go

One of the first things the KeyTransparency sequencer does when initializing a fresh domain (Trillian Log / Map pair), is to put the Map's initial 0'th SignedMapHead into the Log at index 0.  This establishes the 1:1 relationship between Map revisions and the Log indexes at which they must be stored.  If this, however, does not occur, it causes follow on errors that would be nice to catch in a single place. 
Secondly, because clients verify that `SignedMapHead`s are included in the Trillian Log, the key server must not serve any data from a Map revision (SMH) that the Log has not sequenced and signed yet. The `SignedLogRoot` (STH) is effectively the source of truth for what map revision to serve. This was not accurately implemented in `GetEpochHistory` which was using the latest SMH …

Catch log initialized errors

---

cmd/keytransparency-server/main.go
core/keyserver/keyserver.go
impl/integration/env.go

Trilian Logs and Trilian Maps have different Admin interfaces. 
This repipes the KT server to use the appropriate Admin interface for logs and maps.
The integration tests, however, at this time don't have a logEnv (coming soon), so we use mapEnv.Admin for both logs and maps temporarily.

Use separate log and map admin connections in the keyserver

---

cmd/keytransparency-client/cmd/post.go
core/client/grpcc/get_and_verify.go
core/client/grpcc/grpc_client.go
core/client/kt/requests.go
core/client/kt/verify.go
core/integration/client_tests.go
core/integration/monitor_tests.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go
impl/integration/env.go

This PR supports reliable testing and more efficient bandwidth usage.
Rather than blindly re-sending the UpdateEntryRequest every few seconds
until the change is observed, this commit adopts a slightly more
intelligent strategy:
1. Observe current SignedLogRoot
2. Queue update request
3. Wait for a new epoch to be created
4. Query the user's account
5. Compare against the desired state.
a. Wait some more
b. Recreate request and try again
c. Do nothing, it worked :-)
This strategy is more accomadating to non-determinism in the Log.
Because we wait for concrete state changes, we can be confident of what
the resulting values should or should not be, making testing feasible.

Intelligent Update strategy: replace blind Retry with WaitForSTH

---

core/adminserver/admin_server.go
core/adminserver/admin_server_test.go
core/client/client.go
core/client/get_and_verify.go
core/fake/trillian_log_client.go
core/integration/client_tests.go
core/integration/monitor_tests.go
core/keyserver/epochs.go
impl/integration/env.go

Diffbase #917 
The current strategy of using a fake.TrillianLogClient was being a bit _too_ predictable.
By using a real Trillian Log, we uncovered a number of timing and correctness issues.
This is the last of the fixes to use the real `LogEnv`. woohoo!

Use a real Trillian Log in integration tests!

---

core/client/client.go
core/client/verify.go
core/integration/client_tests.go
impl/integration/env.go

This change catches a bug in the client which was not using the correct root for inclusion proof verification.  
This PR 
- Uses a full KT client configured directly from the domain proto.
- Sets and checks unique values for the public keys in user accounts.

Use real Trillian verifier in integration tests

---

core/sequencer/sequencer.go
impl/integration/env.go

Now that log and map initializtion are part of the admin server, this
check and quick-fix are no longer needed. If by this point the map
really is not setup, a serious error has occurred.
This PR also contains a few formatting cleanups.

 Don't fail silently when uninitialized 

---

core/integration/monitor_tests.go
core/monitor/monitor.go
core/monitor/verify.go

This PR cleans up a little bit of the monitor. Many of the more complex functions that used to be manually performed have been moved to the trillian `MapVerifier`.

Use MapVerifier in monitor

---

cmd/keytransparency-monitor/main.go
core/integration/client_tests.go
core/integration/monitor_tests.go
core/monitor/monitor.go
core/monitor/verify.go

This PR slightly reworks the monitor to clarify what the currently trusted log root is. 
It also reworks the integration test to be easier to follow.

Clarify root of trust in monitor

---

core/integration/alltests.go
core/integration/client_tests.go
impl/integration/env.go

Different test environments will run at different speeds.
Therefore it makes sense to make timeout a part of Env.
This PR also expands the use of timeouts to several more
functions which could timeout.

Make Timeout a test env variable.

---

cmd/keytransparency-client/cmd/get.go
cmd/keytransparency-client/cmd/history.go
cmd/keytransparency-client/cmd/post.go
cmd/keytransparency-client/cmd/root.go

Pass user creds into GetClient so that callers can supply their own
creds during testing.

 Invert dependency of userCreds 

---

cmd/keytransparency-client/cmd/hammer.go
cmd/keytransparency-client/cmd/root.go
deploy/kubernetes/server-deployment.yaml

Load test the open source continuous integration server. 
Each operation takes ~2s to complete end to end.
QPS peaked at ~80 and revealed a leaking transaction in the Trillian Map: #944

Add loadtest hammer operation to the client

---

cmd/keytransparency-monitor/main.go
core/adminserver/admin_server.go
core/client/client.go
core/client/get_and_verify.go
core/client/vectors_test.go
core/client/verify.go
core/integration/monitor_tests.go
core/monitor/monitor.go
core/monitor/verify.go

Following google/trillian#1048, use types.LogRootV1 as the local
reference of what the most up-to-date log root is.

Use types.LogRootV1

---

.gitignore
.travis.yml
docker-compose.yml
scripts/deploy.sh

The current docker configuration doesn't cause kubernetes to actually update. 
The reason is that docker only updates when the job configuration changes, not when the `:latest` label points to something else. 
This PR gives each deployment a unique label based on the travis commit, and then it explicitly updates Kubernetes to that tag.

Add commit tags to docker images

---

cmd/keytransparency-client/cmd/hammer.go
core/mutator/entry/entry_test.go
core/mutator/entry/mutation_test.go
core/mutator/entry/mutator.go

Previously, tink types were being registered in tests, but this lead to the unfortunate result that they were missing when run from the binary. 
This PR registers the standard Tink types in the same modules in which they are used.

Register standard tink types

---

cmd/keytransparency-sequencer/main.go
cmd/keytransparency-sequencer/server.go

This PR allows the main thread to call `http.Shutdown`
when the sequencing thread exits.

Exit sequencer when sequencing fails.

---

core/adminserver/admin_server.go
core/adminserver/admin_server_test.go
core/fake/domain_storage.go
core/monitor/monitor.go
impl/sql/domain/storage.go

This PR addresses some mid-CreateDomain issues that were cropping up in production and seeks to increase test cases coverage. 
* Handle the AlreadyExists Case
* Handle a mid-tree creation failure by deleting other tree.
* Add unit testing with mocks.

Strengthen CreateDomain

---

README.md

Update both the README and the default client configuration to point to the continuous integration server.

Update default paths in README

---

cmd/keytransparency-client/cmd/hammer.go
core/client/client.go
core/client/hammer/hammer.go

The previous few PRs (#974  #973 ) migrated authentication and authorization from `/core` to implementation specific grpc interceptors. 
This PR refactors the `PerRPCCredentials` creation out of `/core/client` into implementation specific `/cmd/keytransparency-client`.   The `CallOptions` even has the flexibility to not return any options for situations where an implementation has chosen to not implement authorization controls.

Move userCreds func to cmd/client

---

core/client/client.go
core/integration/alltests.go
core/integration/client_tests.go
core/integration/monitor_tests.go
gometalinter.json
impl/authentication/fake.go
impl/integration/env.go

Move the `WithFakeAuth` function from `core/integration` to `GetOpts` in `impl/integration/env`. All credential information is now deployment specific since #974. 
This PR also
-  introduces a new linter to make sure that nothing in `core` imports things from `impl`. 
- Removes the `TestUpdateValidation` integration test because it was only testing whether the authentication code was working. This is now checked in the authentication packages themselves.

Move get authentication function to `/impl`

---

core/client/hammer/hammer.go

Move the increment variable before the wait at the end of the function.
The loop was creating the correct number of jobs, but because the wait is at the end of the loop, real-time statistics were one less than they should be.

Fix hammer off-by-one

---

core/client/client.go
core/client/hammer/hammer.go
impl/integration/env.go

A domain will never create new epochs faster than MinPeriod, so there's
no point in querying the server faster than that.

Configure backoff parameters from Domain info

---

cmd/gen-test-vectors/main.go
core/integration/client_tests.go
core/integration/monitor_tests.go
core/mutator/mutator.go
core/sequencer/sequencer.go
impl/integration/env.go
impl/sql/mutationstorage/queue.go

Some queue implementations are asynchronous.  Therefore tests need to wait for the expected number of items to arrive at the receiver before continuing. 
This PR also resolves another race condition: During env setup, `seq.NewReceiver` creates a map revision, so now we wait for this revision to complete before returning `env`.  As a result, we also need to add 1 to the list history test expectations.

Assert number of items in queue during tests

---

core/adminserver/admin_server.go
core/adminserver/admin_server_test.go
core/sequencer/sequencer.go
core/testdata/domain.json

Now that PREORDERED_LOGs are a thing, we can insert map roots into the
log in a deterministic way, and remove the sword of Damocles that was
previously there due to non-deterministic log sequencing

Place MapRoots into Log by index

---

cmd/keytransparency-sequencer/server.go
core/integration/monitor_tests.go

Integration test timeouts are defined by `env.Timeout` so they it can be adjusted according to each environment's needs.

Fix test timeout

---

core/adminserver/admin_server.go
impl/integration/env.go

Make monitoring graphs easier to use by setting the trillian tree display name, which is used as the primary key.

Set tree display names

---

cmd/keytransparency-sequencer/main.go
core/sequencer/sequencer.go
impl/integration/env.go

Control the maximum number of mutations the Key Transparency sequencer processes per map revision.
Also adds visibility into the number of mutations the sequencer is attempting to process during each map revision.

Add batch-size flag and metric

---

core/sequencer/sequencer.go
impl/sql/mutationstorage/queue.go

Sequencing errors were being info logged rather than err logged.
Also wraps errors during sequencing to better identify them

Write glog.Errorf for errors

---

.travis.yml

Travis is having trouble with GCE's new method for authorizing docker. 
Take the opportunity to update .travis 
- Avoid `sudo` by installing docker-ce with apt. This allows travis to use faster, containerized builds
- Install `docker-compose` with --user without a python environment. I think this helps download the latest version.

Fix travis gcloud docker auth

---

impl/sql/mutationstorage/queue.go
impl/sql/mutationstorage/queue_test.go

Use a slightly simpler loop for sending multiple batches.
The previous implementation used a more chanel with a small buffer.
This worked as long as the select loop never chooses min.C when it
could have selected the more channel.

Fix queue deadlock

---

.gitignore
.travis.yml
Makefile
coverage.sh

Go 1.10 removes the need to run each test separately with the `-coverprofile` flag.
This also makes it easier to set environment variables for tests.

Add integration test to code coverage metrics

---

core/adminserver/admin_server.go
core/sequencer/sequencer.go

google/trillian#1224 requires clients to explicity state what trusted
root to initially use when verifying responses from the trillian log.
This PR uses an empty root, effectively trusting the first observed
log root.

Explicitly trust the first observed log root

---

core/integration/alltests.go
core/integration/client_tests.go
core/integration/monitor_tests.go
core/sequencer/sequencer.go
impl/integration/env.go

This PR removes `Env.Receiver` which was previously being used for fine-grained control over what mutations were part of a batch. The presence of `Receiver` in `Env` prevented integration tests from being run against live servers.
This PR replace `Receiver` with 
a) Real sequencing behavior when the exact batch composition is not being tested.
b) Calls to the new`sequencer.Server.CreateEpcoh` API to create new epochs directly when exact batching is needed.

Restrict integration.Env to only grpc clients

---

cmd/keytransparency-sequencer/main.go
core/sequencer/sequencer.go

Some server frameworks support periodic callbacks directly.

Expose single shot `CheckForNewDomains` function

---

core/adminserver/admin_server.go
core/adminserver/admin_server_test.go
impl/integration/env.go

At the end of an integration test, soft-delete the domain and the corresponding Trillian trees. 
TODO: 
- Run doman and tree garbage collection.

Cleanup domains after integration test

---

cmd/keytransparency-client/cmd/post.go
cmd/keytransparency-client/cmd/root.go

Fixes a bug where the client was not sending oauth user credentials.
Post #975, client creds do not need to be passed with each RPC, and as
such, an authenticated, yet anonymous mode of authentication is no
longer needed, we can just use unauthenticated calls for the public api.
If we need to bring this back at a later point for spam reasons, we can.
In the meantime, deleted code is best code.

Remove service-key

---

cmd/gen-test-vectors/main.go

gen-test-vectors would fail if an update was successfully applied before the 6 second timeout, and had dead code which would wait for that update again.

Fix gen-test-vectors

---

core/crypto/commitments/commitments.go

The commitment also includes appID as a namespace, updating the comment to reflect that.

Fix commitment scheme comment

---

cmd/keytransparency-client/cmd/root.go
core/adminserver/admin_server.go
core/testdata/domain.json
core/testdata/getentryresponse.json

Added to Trillian in https://github.com/google/trillian/pull/1266. Also regenerates test vectors with the new hash strategy.

Use CONIKS_SHA256 hash strategy by default

---

core/adminserver/admin_server_test.go
impl/integration/env.go

google/trillian#1272 added an experimental argument to NewMapEnv. Fixes adminserver and integration build errors.

Add missing argument to NewMapEnv

---

core/client/verify.go

Found using https://go-critic.github.io/overview#unslice-ref

Simplify s[:] to s where s is a slice

---

core/keyserver/keyserver.go

The storage layer uses the NotFound GRPC status rather than sql.ErrNoRows. These errors were being converted into Internal error codes.

Propagate NotFound error correctly for missing domains

---

impl/authorization/authorization.go

A prior pull request simplified the authentication library by removing
action labels and only performing group inclusion checks. This PR removes 
the old action label from the format string.

Fix format string bug

---

core/client/client.go
core/keyserver/keyserver.go

Rather than returning a complex data structure that indicates that the
current revision is greater than the one referenced in the request,
return an error code that the client can parse.
Fixup of #1050

Return error code for old requests.

---

cmd/gen-test-vectors/main.go
cmd/keytransparency-client/cmd/keys.go
cmd/keytransparency-client/cmd/post.go
core/client/hammer/hammer.go
core/integration/client_tests.go
core/managementserver/server.go
core/mutator/entry/mutation.go
core/mutator/entry/mutator.go
core/sequencer/server_test.go
core/testutil/tink.go
impl/sql/keysets/keysets.go
impl/sql/keysets/keysets_test.go

Follows API cleanup in Tink per google/tink#93.
It seems like Tink removed the capability to read/write encrypted keysets, so I've had to use insecure.KeysetHandle in a few places.

Merge Tink API changes

---

cmd/gen-test-vectors/main.go
core/client/verify_test.go
core/testdata/domain.json
core/testdata/getentryresponse.json
core/testdata/types.go

The trusted log root will fall behind a bit to make consistency proofs
more interesting.
Also changes the testdata generator to only open and write files once,
rather than overwriting the same file multiple times.

Generate consistency proofs in test vectors

---

.travis.yml

The multiple statements inside the bash if block are being treated as one continuous command.
This PR separates them properly with semicolons.
Fixes #1060

Add ';' to separate if statements

---

core/mutator/mutator.go

We are no longer using Spanner style callbacks and can remove this interface now.

Removed Spanner callback interfaces

---

impl/sql/mutationstorage/mutations.go
impl/sql/mutationstorage/queue.go

Since we are no longer using a queue, but a log of messages, we
shouldn't be deleting messages.

Remove DeleteMessages API

---

cmd/keytransparency-monitor/Dockerfile
cmd/keytransparency-sequencer/Dockerfile
cmd/keytransparency-server/Dockerfile
deploy/kubernetes/monitor-deployment.yaml
docker-compose.yml

Having an unused flag in the deploy scripts causes the binary to immediately crash.

Remove unused poll-period flag

---

core/adminserver/admin_server_test.go

Use the same error code as the Trilian code base does for uninitalized
trees while waiting for the tree to be initialized.
This follows change google/trillian#1333

Use FailedPrecondition in mock Trillian server.

---

cmd/gen-test-vectors/main.go
cmd/keytransparency-sequencer/main.go
core/integration/client_tests.go
core/sequencer/sequencer.go

Removes the previous behavior of stopping the recurring call if the
called function returned an error. This behavior was causing the server
to stop processing while appearing to be healthy.
Require the internal function to handle it's errors or shutdown.

Keep PeriodicallyRun running until ctx is canceled

---

core/sequencer/server.go

Fixes an important TODO that's necessary for the idempotency of `CreateRevision`

Read map at a specific revision

---

cmd/keytransparency-server/main.go
core/client/client.go
core/keyserver/keyserver.go
core/monitor/verify.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go
core/mutator/entry/mutator.go
core/mutator/entry/mutator_test.go
core/mutator/mutator.go
core/sequencer/server.go
core/sequencer/server_test.go
impl/integration/env.go

Replaces the mutation interface with a reduce function type.
It is not generally true that a struct based mutation function
will work. This change clarifies that a bit and reduces code stutter.
This is part of making a multi-leaf mutation possible #1122

 Simplify the Reduce function interface

---

core/keyserver/keyserver.go
core/keyserver/revisions_test.go
core/mutator/mutator.go
impl/sql/mutationstorage/mutations.go
impl/sql/mutationstorage/queue.go
impl/sql/mutationstorage/queue_test.go

This improves the write performance from ~10k entries/s to ~100 k/s
Before
```
BenchmarkSend-8 		10000 			101075 ns/op
```
After
```
BenchmarkSend/1-8 	   	   20000	     92531 ns/op
BenchmarkSend/2-8 	   	   10000	    104603 ns/op
BenchmarkSend/4-8 	   	   10000	    125030 ns/op
BenchmarkSend/8-8 	   	   10000	    164034 ns/op
BenchmarkSend/16-8         	    5000	    247246 ns/op
BenchmarkSend/32-8         	    3000	    406327 ns/op
BenchmarkSend/64-8         	    2000	    730439 ns/op
BenchmarkSend/128-8        	    1000	   1330174 ns/op
BenchmarkSend/256-8        	     500	   2521275 ns/op
```
Part of #1229

Implement batched queue mutation

---

cmd/keytransparency-sequencer/main.go
cmd/keytransparency-sequencer/server.go
core/sequencer/sequencer.go
core/sequencer/server.go
impl/integration/env.go

By making calls through the rpc layer, we produce rpc layer metrics through prometheus about `DefineRevision`, `CreateRevision`, and `PublishRevision`.  These include periodicity, failure codes, latency, and a whole range of other metrics.

Use Loopback Connection in Sequencer

---

core/sequencer/sequencer.go
core/sequencer/sequencer_api.proto
core/sequencer/sequencer_go_proto/sequencer_api.pb.go
core/sequencer/server.go
core/sequencer/server_test.go
core/sequencer/trillian_client.go

Rework Sequencer API
- Consistency of `Revision` terminology
- Create `DefineRevisions` API
- Return metrics in the API responses

Cleanup Sequencer API

---

core/client/batch_client.go
core/client/batch_get_and_verify.go
core/client/client.go
core/client/hammer/hammer.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go
core/sequencer/server_test.go

A shortcut for creating brand new users that avoids the round trip that's needed to fetch the current user state.

Client: BatchCreateUser

---

cmd/gen-test-vectors/main.go
cmd/keytransparency-client/cmd/post.go
core/client/batch_client.go
core/client/client.go
core/client/hammer/hammer.go
core/frontend/frontend.go
core/integration/client_tests.go
core/integration/monitor_tests.go
core/mutator/entry/mutation.go
core/mutator/entry/mutation_test.go
core/mutator/entry/mutator_test.go
core/sequencer/server_test.go
core/testutil/tink.go

This PR swaps out uses of  `tink.KeysetHandle` which references loaded key material for `tink.Signer`  which is an interface that permits remote key material and lazy loaded keys.  As a result, the servers can start without blocking on key material loading.

Lazy load key material

---

core/adminserver/admin_server.go
core/adminserver/admin_server_test.go
core/directory/directory.go
core/keyserver/keyserver.go
core/keyserver/keyserver_test.go
core/keyserver/revisions.go
core/sequencer/trillian_client.go
impl/sql/directory/storage.go
impl/sql/directory/storage_test.go

* Romeved from directory table:
MapId, LogId fields
* Added to directory table:
Map, Log fields with type BLOB
* Removed fecth request to TrillianTree
Fixes: https://github.com/google/keytransparency/issues/1152

Store trillian map,log trees in DB

---

core/adminserver/admin_server.go
core/adminserver/admin_server_test.go

Removed unused field `deleted` from Trillian tree struct we store in our DB.
Removed part of the tests related to this field.

Remove deleted status from map and log trees

---

docker-compose.yml

Exposed my-sql DB port 3306 on same port outside.
At least it fails on `go generate ./core/testdata` step.
Fixes: https://github.com/google/keytransparency/issues/1182

Expose mysql docker container port

---

core/crypto/tinkio/pem.go
core/testutil/tink.go

Migrate the uber-hacky `testutil` functions for creating tink keysets to a much less hacky object that uses the PEM `tink.KeysetReader` API.

PEM tink.KeysetReader

---

cmd/keytransparency-server/main.go
core/keyserver/keyserver.go
core/sequencer/server.go
impl/integration/env.go

New and improved metrics that support
- Rate of log entries being read by the sequencer
- Rate of map leaves being written by the sequencer
- Rate of map revisions being written by the sequencer
- High watermarks for each input log as they are being 
- Written to
- Defined in a batch definition for a revision
- Written to a map revision

Improved Metrics

---

README.md

Some proposals to address #1158.
1. Consistent usage of `--[flag]`
1. Be more explicit about the key set password: `${PASSWORD}` rather than `password`
1. Added clarity to the use of an implicit URL for the Key Transparency server (`35.202.56.9:443`)
1. L119 and L120 incorrectly refer to the published server but ought -- I think? -- reference the locally running service. Revised the URLs.
1. Duplicated these as LL84-86 to use the public Key Transparency server
1. Propose (haven't done) adding commands to create and test a specific email address rather than `user@domain.com` and `foo@bar.com`
Unsures:
1. L40 reads `Generate a private key` and this complements L50 `Publish the public key` but these aren't (I think and not in the example given) a public-private key pair?
1. The example posts …

Proposed changes to README

---

cmd/keytransparency-client/cmd/post.go

Note that this is an incomplete fix
Before
```
go run ./cmd/keytransparency-client/main.go post dazwilkin@google.com --client-secret=/Users/gbelvin/Downloads/client_secret_442418751519-0dgrd0631a9e0n1289g2ebp9evg6ln2m.apps.googleusercontent.com.json --insecure --data='dGVzdA==' --password=${PASSWORD} --kt-url=0.0.0.0:443 --verbose --logtostderr --timeout=10s
Go to the following link in your browser then type the authorization code:
Error: context deadline exceeded
```
After
```
go run ./cmd/keytransparency-client/main.go post dazwilkin@google.com --client-secret=/Users/gbelvin/Downloads/client_secret_442418751519-0dgrd0631a9e0n1289g2ebp9evg6ln2m.apps.googleusercontent.com.json --insecure --data='dGVzdA==' --password=${PASSWORD} --kt-url=0.0.0.0:443 --verbose --logtostderr
Go to the …
```

Don't timeout users entering OAuth info

---

README.md
docker-compose.override.yml
docker-compose.prod.yml
docker-compose.yml

Rather than setting up a full mysql instance, which can be a hassle, support testing against the local database, run by docker with `docker-compose up -d db`. 
The tests require the mysql database to have an empty root password, which is not suitable for production, so this PR splits out the docker-compose file into a separate `dev` and `prod` configurations: 
- dev: `docker-compose up`
- prod: `docker-compose up -f docker-compose.yml docker-compose.prod.yml`
This feature depends on google/trillian#1425
Fixes #1184

Support testing with docker

---

core/keyserver/keyserver.go
core/keyserver/revisions_test.go
impl/sql/mutationstorage/queue.go
impl/sql/mutationstorage/queue_test.go

Add an interface to return metadata about writes to the mutation queue so it can be exposed in the keyserver as a metric.

Set write watermark in keyserver

---

core/crypto/tinkio/pem.go

Fix the build since tink moved a bunch of stuff to testutil. 
This file should eventually not have any references to `testutil`. 
The proposed solution is to merge this file with the tink code base.

Tink updates

---

cmd/keytransparency-client/cmd/hammer.go
cmd/keytransparency-client/cmd/root.go
core/client/hammer/hammer.go

Allow custom address definitions that are more complex than `string`.

Factor out addr from DialFunc

---

.travis.yml

fixes #1214 
I fix .travis.yml to be able to use xenial images, docker and docker-compose which are default package in this images.
I don't know how fast build it using xenial images...
https://travis-ci.com/u5surf/keytransparency/jobs/178577965

update travis.yml to xenial

---

README.md
cmd/keytransparency-client/cmd/hammer.go
cmd/keytransparency-client/cmd/keys.go
cmd/keytransparency-client/cmd/post.go

Fixes https://github.com/google/keytransparency/issues/1213
Fixes https://github.com/google/keytransparency/issues/1206
Added `keyset-file` flag to specify keyset file path and name, for CREATE, LIST, POST and HAMMER commands.
Added small description of the new flag to README

Added keyset-file flag tp specify file path and name

---

core/mutator/entry/mutator.go

#1224 Accidentally swapped the argument order of the existing values in the map and the new values being reduced.

Fix reversed arguments

---

core/sequencer/runner/native.go
core/sequencer/server.go

Perform the mapping operation on LogItems only once. 
Flow before this PR:
1. Read Log Items
2. Map Log Items into `[]index` and `[]EntryUpdate`
3. "Apply"
3a. Map `EntryUpdate` into `IndexedValue`
After:
1. Read Log Items
2. Map Log Items into `[]IndexedValue`
3. Reduce `[]IndexedValue` to `[]index`
4. Reduce `[]IndexedValue`

Simplify MapLogItems

---

core/api/v1/frontend.proto

"*" maps all request fields not captured by the path.

Fix invalid http.body mapping for KeyTransparencyFrontend.QueueKeyUpdate

---

core/sequencer/server.go
core/sequencer/server_test.go

If two updates to the same user occurred during the same batch, the sequencer would request the same index in the map multiple times, causing subsequent verifications to fail.
Adds a failing test and then a fix.
Fixes #1225

Fix: Allow multiple updates to the same user in the same batch

---

core/client/client.go
core/mutator/mutator.go
core/sequencer/runner/native.go
core/sequencer/server.go

Fold the nebulously named `ApplyMutations` into separate MR functions. 
This makes `ApplyRevision` a contiguous series of MR steps that we can optimize and add metrics to going forward.

Complete ApplyRevisions MR pipeline

---

cmd/keytransparency-server/main.go
impl/authentication/google.go
impl/authentication/google_test.go

gAPI.New was deprecated and replaced with gAPI.NewService in
googleapis/google-api-go-client#d827405e6070b8f323fa8681174e93f0195b7961

Transition off of deprecated gAPI.New

---

core/sequencer/runner/native.go
core/sequencer/runner/native_test.go
core/sequencer/server.go
core/sequencer/server_test.go

This PR adds metrics at each stage of the sequencing pipeline to help identify issues when things get stuck in the middle of the pipeline.

Add metrics for each stage of the sequencing pipeline

---

core/mutator/entry/mutator.go
core/sequencer/runner/native.go

Add canonical error codes to the errors that may occur during sequencing.
The main purpose of this is to expose a metric that can export the numbers of sequencing errors that are:
- InvalidArgument - various kinds of data corruption or user error.
- Internal - conditions that we expect to never happen.

Add Canonical Err Codes

---

core/sequencer/server.go

-Add an additional histogram metric to measure latency of ApplyRevision function
--Overall ApplyRevisionLatency
--ReadBatch
--GetAndVerifyMapLeavesByRevision
--SetLeavesAtRevision

Add latency metrics to ApplyRevisions in Sequencer

---

core/keyserver/keyserver.go
core/keyserver/revisions.go

Update some error cases in BatchGetUser to properly return client errors for invalid input.

Update some error cases in BatchGetUser

---

CODEOWNERS

CODEOWNERS automatically assigns reviewers but it also requires an LGTM from
one of those reviewers, regardless of other LGTMs.
Remove single point of failure by expanding code ownership to include the whole
team.

Set default code reviewer to @google/keytransparency

---

core/keyserver/keyserver.go

This distinguishes it from the metric with the same name in the sequencer server.

Add a prefix to keyserver metric name

---

core/sequencer/server.go

To keep from timing out in the case that the sequencer falls behind in its job. Limit how much catchup we attempt in any given RunBatch call.

Limit the amount of catch-up work done in RunBatch

---

cmd/keytransparency-sequencer/main.go
core/sequencer/sequencer.go
core/sequencer/server.go

Moved PublishRevision out of RunBatch and created its own function to call periodically. Publishing to the log and writing to the map are independent actions.

 Separate Log Revision Writes from Map Writes

---

core/integration/monitor_tests.go

Need to call PublishRevisions explicitly now that it has been separated from RunBatch.

Fix broken test in monitor_tests.go

---

core/integration/client_tests.go

One more fix to client_tests.go to add explicit calls to PublishRevisions.

Fix client_tests.go now that RunBatch and PublishRevisions are split

---

core/keyserver/revisions.go

Remove an extra round trip in every RPC path.

Fetch the log root and its consistency proof in one go

---

core/keyserver/revisions.go

Don't return `codes.Internal` when we don't need to

Pass along the underlying error codes

---

core/mutator/entry/mutator.go

When a mutation for a single entry is invalid it will produce both an
InvalidArgument error because of an invalid hash, and this Unknown error
because there are no mutations to apply. This double counting is
confusing.

Don't double count errors

---

core/client/batch_client.go
core/integration/client_tests.go
core/keyserver/keyserver.go

This will help us create more fake traffic for load testing.
Profiling these functions has revealed a significant amount of time being spent in running the VRF functions.

Parallize functions in the BatchCreateUser flow

---

core/client/batch_get_and_verify.go

This produces a 7x speedup for batches of 1000 on a 12 core computer. 
Before: 15s
After: 2s

Parallize VerifyBatchGetUserIndex

---

core/keyserver/keyserver.go
core/keyserver/keyserver_test.go

Avoid using batch APIs where the single shot API would work.
This will help clarify server performance by keeping batch and single user traffic separate.

Use new trillian.GetLeaf API

---

core/sequencer/server.go
core/sequencer/server_test.go
core/sequencer/trillian_client.go
go.mod
go.sum

It's not necessary to fully verify the results from the Trillian Map inside the sequencer because 
this effort is duplicated by clients.
Depends on google/trillian#1647

Use GetMapLeavesNoProof

---

cmd/keytransparency-monitor/Dockerfile
cmd/keytransparency-sequencer/Dockerfile
cmd/keytransparency-server/Dockerfile
docker-compose.yml

Triggered by my challenges using KeyTransparency's (KT's) docker-compose (#1300)
This is a proposal to streamline the use of docker-compose and the container images.
It will *not* (yet) work as-is.
The CI|CD deployment rarely works and the KT server (`35.202.56.9:443`) is generally inaccessible. This makes the need for a user-deployable mechanism more important. The solution for docker-compose exists and is the easiest solution.
The use of Go Modules (appears to) cause problems with the docker-compose builds. The Dockerfiles were being referenced from `github.com/google` and this directory contains no `go.mod` files. This resulted in issues for the `docker build` commands. Splitting KT and Trillian (see #2) allows the build context to be more appropriately set to …

Proposal to refine docker deployment

---

core/keyserver/paginator_test.go
core/keyserver/revisions_test.go

Towards github.com/google/trillian#1738.

Fix proto copying in revisions and paginator tests.

---

core/client/client.go
core/client/mutations.go
core/monitor/monitor.go

All verifications should be rooted in the last verified log root.
Pass already verified `mapRoot` to `RevisionMutations`.  There's no need to re-verify it without the context of a last verified log root.

Remove VerifySignedMapRoot from VerifierInterface

---

core/mutator/entry/mutation.go
core/mutator/entry/mutator.go
core/mutator/entry/mutator_test.go

The hash chain in user entries is not currently being used.  `Entry.Previous`
was intended to help make account history verification efficient, but it did
not meet that goal.
In the meantime, `Entry.Previous` enforces quite a tight sequence of get,
modify, update.  Any delay in Key Transparency sequencing causes these updates
to fail, and continuously retrying exacerbates the issue.

Make check-set mutation semantics optional

---

core/client/batch_get_and_verify.go
core/client/client.go
core/client/client_test.go
core/client/get_and_verify.go
core/client/verifier/verifier.go
core/client/verifier/verifier_test.go
core/integration/client_tests.go
core/monitor/monitor.go

This PR establishes a nice API pattern:
`VerifyX(VerifiedDataFromPreviousStep,  UnverifiedInputData) VerifiedDataForNextStep`
It is also important because it allows us to verify a log root once, while verifying many map roots in VerifyListHistory. 
By establishing a 1:1 relationship between sending requests and verifying log roots, we setup ourselves nicely for a refactoring of the log root tracker into a separate package.

 Split VerifyRevision into Verify{LogRoot,MapRevision

---

core/client/client.go
core/client/client_test.go
core/client/get_and_verify.go
core/client/verifier/pairs.go
core/client/verifier/verifier_test.go
core/integration/client_tests.go

Remove duplicate code by creating RPC pair verification functions

Pair verifier functions

---

cmd/keytransparency-monitor/main.go
core/client/get_and_verify.go
core/client/mutations.go
core/integration/monitor_tests.go
core/monitor/monitor.go
core/monitor/monitor_test.go
core/monitor/verify.go

By verifying revisions inside of StreamRevisions, 
we can reuse VerifyGetRevision and have better control
over the updating of LogRoot

Verify Revisions in StreamRevisions

---

core/client/batch_get_and_verify.go
core/client/client.go
core/client/client_test.go
core/client/get_and_verify.go
core/client/tracker/tracker.go
core/client/tracker/tracker_test.go
core/client/verifier/pairs.go
core/client/verifier/verifier.go
core/client/verifier/verifier_test.go
core/integration/client_tests.go
core/monitor/monitor.go

This PR isolates root tracking inside a new `tracker` package. 
By putting all root tracking behind an interface, we can implement alternate, multi-threaded root trackers.  #1311

Extract log tracking into separate package 

---

.travis.yml
cmd/keytransparency-monitor/Dockerfile
cmd/keytransparency-sequencer/Dockerfile
cmd/keytransparency-server/Dockerfile
go.mod
go.sum

Reverts google/keytransparency#1330
This worked for a while, but then GOPROXY started returning 410's for pseudo-versions deep in the dependency graph. 
cc @ FiloSottile

Revert "Turn on GOPROXY"

---

scripts/integration.sh

Add UNAVAILABLE to the list of HTTP codes the integration test retries on

Improve integration script reliability

---

cmd/keytransparency-sequencer/main.go
core/adminserver/admin_server.go
core/adminserver/admin_server_test.go
impl/integration/env.go

This change puts batch number 0 to storage when a directory is created.

Initialize mutations batch 0 with zero watermarks

---

core/sequencer/server.go
core/sequencer/server_test.go

The latest batch definition should start from the highest defined batch, not the highest applied batch. 
Related to #1335

Read batch definitions from batch storage

---

deploy/kubernetes/db-deployment.yaml
deploy/kubernetes/init-pod.yaml
deploy/kubernetes/log-server-deployment.yaml
deploy/kubernetes/log-signer-deployment.yaml
deploy/kubernetes/map-server-deployment.yaml
deploy/kubernetes/monitor-deployment.yaml
deploy/kubernetes/prometheus-deployment.yaml
deploy/kubernetes/sequencer-deployment.yaml
deploy/kubernetes/server-deployment.yaml
scripts/deploy.sh

Fix deployment script. Use gcr.io consistently

---

core/integration/storagetest/batch.go
impl/sql/mutationstorage/mutations_test.go
scripts/integration.sh

Some storage implementations require a domain setup step
This switch allows the storage factory to do the nessesary
setup for the test.

storagetest factory now takes domainID

---

cmd/keytransparency-monitor/Dockerfile
cmd/keytransparency-sequencer/Dockerfile
cmd/keytransparency-server/Dockerfile

Make things consistent. The rest of the project is using go 1.13

Bump docker images to go1.13

---

core/sequencer/trillian_client.go

KT only uses the `WriteLeaves` RPC, so `SetLeaves` can be removed.

client: Remove unused SetLeavesAtRevision

---

cmd/keytransparency-sequencer/main.go
cmd/keytransparency-server/main.go
core/integration/storagetest/batch.go
core/integration/storagetest/mutation_logs.go
core/integration/storagetest/mutation_logs_admin.go
go.mod
impl/integration/env.go
impl/sql/directory/storage_test.go
impl/sql/mutationstorage/mutation_logs_test.go
impl/sql/open.go
impl/sql/testdb/testdb.go
impl/sql/testdb/testdb_test.go

"Test what we use" 
By testing against a real MySQL database instead of SQLite, I discovered a subtle implementation difference in the behavior of `AffectedRows`, requiring a MySQL driver flag `ClientFoundRows` to be set to achieve the desired behavior

Use and test the same MySQL connection that main.go uses 

---

core/integration/storagetest/mutation_logs.go
core/keyserver/keyserver.go
core/keyserver/revisions_test.go
impl/sql/mutationstorage/mutation_logs.go
impl/sql/mutationstorage/mutation_logs_test.go

The storage layer should not have a dependency on the frontend library.
By breakinig this dependency, we can avoid import cycles in later PRs.

Break layering violation by using native types

---

core/sequencer/server_test.go

Fix bug in tests. Previously, the metrics just happened to be 
registred based on the order tests were run in.

Init metrics for whole test file

---

core/integration/storagetest/mutation_logs.go
core/keyserver/keyserver.go
core/keyserver/revisions_test.go
impl/sql/mutationstorage/mutation_logs.go
impl/sql/mutationstorage/mutation_logs_test.go

Allow clients to specify the mutation input log
This permits quality of service prioritization because
input logs are processed in low to high order.

Move the responsibility to pick an input log from storage to the frontend

---

core/sequencer/runner/native_test.go

Generated protobuf messages contain internal data structures
that general purpose comparison functions (e.g., reflect.DeepEqual,
pretty.Compare, etc) do not properly compare. It is already the case
today that these functions may report a difference when two messages
are actually semantically equivalent.
Fix all usages by either calling proto.Equal directly if
the top-level types are themselves proto.Message, or by calling
cmp.Equal with the cmp.Comparer(proto.Equal) option specified.
This option teaches cmp to use proto.Equal anytime it encounters
proto.Message types.

Fix generic comparisons on protobuf messages

---

core/integration/storagetest/mutation_logs.go
core/integration/storagetest/mutation_logs_reader.go
impl/memory/mutation_logs_test.go
impl/sql/mutationstorage/mutation_logs.go
impl/sql/mutationstorage/mutation_logs_test.go

Standardize on quantums of time.Microsecond

Support and test mutation log queries at intermediate timestamps

---

core/keyserver/paginator.go
core/keyserver/paginator_test.go
core/keyserver/revisions.go
core/keyserver/revisions_test.go
core/sequencer/metadata/sourceslice.go
core/sequencer/metadata/sourceslice_test.go
core/sequencer/server.go
core/sequencer/server_test.go

This PR effectively makes pb.Watermarks a private object.
By only accessing the watermarks proto through a helper library, we give ourselves the ability to define clear rules for what valid watermarks are.

Library for converting time.Time to sequencer watermarks

---

core/keyserver/revisions_test.go
core/sequencer/metadata/sourceslice.go
core/sequencer/metadata/sourceslice_test.go
core/sequencer/sequencer_api.proto
core/sequencer/sequencer_go_proto/sequencer_api.pb.go

Some time ago, different instances of Key Transparency had different units / meanings for the `int64`'s stored in `MapMetadata`.   When we switched to `time.Time` based APIs in 575344f256a6ca2e5fea3a9c3025aa69d57f63e3,  the open source `MapMetadata` silently acquired a definition of unix nanos and this change nearly caused an outage. 
This PR synchronizes the open source definition of `MapMetadata` with the unix micro one we had been defacto using internally.

Define watermarks as micros

---

core/sequencer/server.go

Emitting the wrong number of dimensions will cause an error.

Don't emit metric err on read err

---

cmd/keytransparency-monitor/main.go
core/integration/monitor_tests.go

Was removed in https://github.com/google/trillian/pull/1997. Sorry, wasn't aware it was in use in KT.

Fixups for deleted test constructor in trillian repo

---

core/keyserver/keyserver_test.go
core/keyserver/revisions_test.go

Protobufs should not be compared with `reflection.DeepEqual` which is that the `gomock` matchers do by default.

Use ProtoEqual for gomock reflection equality

---

core/integration/storagetest/mutation_logs.go
impl/memory/mutation_logs.go

- Remove dependency on time.Now
- Check validity of insert timestamps
- Support implementations based on unix seconds

Improve mutation log integration tests

---

.travis.yml
scripts/deploy.sh
scripts/docker-compose_test.sh
scripts/kubernetes_test.sh

- Build docker images
- Inject fresh images into kind (k8 in docker)
- Set docker image tags

Test against fresh builds

---

scripts/deploy.sh

Allow `scripts/deploy.sh` to be run locally by setting environment
variables usually supplied by Traivs

Set TRAVIS_COMMIT if unset

---

deploy/kubernetes/base/db-deployment.yaml
deploy/kubernetes/base/db-service.yaml
deploy/kubernetes/base/init-pod.yaml
deploy/kubernetes/base/log-server-deployment.yaml
deploy/kubernetes/base/log-server-service.yaml
deploy/kubernetes/base/log-signer-deployment.yaml
deploy/kubernetes/base/log-signer-service.yaml
deploy/kubernetes/base/map-server-deployment.yaml
deploy/kubernetes/base/map-server-service.yaml
deploy/kubernetes/base/monitor-deployment.yaml
deploy/kubernetes/base/monitor-service.yaml
deploy/kubernetes/base/prometheus-deployment.yaml
deploy/kubernetes/base/prometheus-service.yaml
deploy/kubernetes/base/sequencer-deployment.yaml
deploy/kubernetes/base/sequencer-service.yaml
deploy/kubernetes/base/server-deployment.yaml
deploy/kubernetes/base/server-service.yaml

The Kubernetes configs were originally created with `kompose convert` but the k8 configs have since significantly diverged due to sidecars, local and gke specific configs. 
This PR removes kompose metadata that is no longer correct. 
The k8 configs and the docker-compose configs are currently maintained by hand because there is not an exact 1:1 feature mapping between them.

Remove kompose k8 cruft

---

cmd/keytransparency-monitor/main.go
cmd/keytransparency-sequencer/main.go
cmd/keytransparency-sequencer/server.go
cmd/keytransparency-server/main.go
cmd/serverutil/healthz.go
cmd/serverutil/readyz.go
cmd/serverutil/serverutil.go
deploy/kubernetes/base/monitor-deployment.yaml
deploy/kubernetes/base/sequencer-deployment.yaml
deploy/kubernetes/base/server-deployment.yaml
docker-compose.yml
scripts/docker-compose_test.sh
scripts/kubernetes_test.sh

As a precondition for using a GKE load ballancer, we must define readiness probes.
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#limitations
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Setup liveness and readiness k8 probes

---

deploy/prometheus/Dockerfile

Prometheus runs as nobody, which meant it couldn't read the config files in /etc/prometheus. Change ownership of the files we place there so that it can read them.

Fix permissions on Prometheus config files

---

scripts/gen_monitor_keys.sh
scripts/gen_server_keys.sh
scripts/prepare_server.sh

Since Go Modules became supported by KT, it should also support being checked out to an arbitrary location.

Fix scripts to not depend on KT being in $GOPATH

---

cmd/healthcheck/main.go
cmd/keytransparency-monitor/Dockerfile
cmd/keytransparency-sequencer/Dockerfile
cmd/keytransparency-server/Dockerfile
docker-compose.yml
scripts/docker-compose_test.sh

- cmd/healthcheck binary to make http(s) requests.
- Move HEALTHCHECK to Dockerfile
- Verify health in test scripts
- Remove unsupported Trillian health checks https://github.com/google/keytransparency/issues/1200

Fix Docker HEALTHCHECK

---

scripts/deploy.sh
scripts/gcrgc.sh

Delete docker images older than 30 days

Cleanup old docker images

---

codecov.yml

Code coverage seems to bounce around a bit.
Allow it do bounce around by 1% without going red.

Less flakey codecov

---

cmd/keytransparency-monitor/Dockerfile
cmd/keytransparency-monitor/main.go
cmd/keytransparency-sequencer/main.go
cmd/keytransparency-sequencer/server.go
cmd/keytransparency-server/main.go
cmd/serverutil/serverutil.go
deploy/kubernetes/base/monitor-deployment.yaml
docker-compose.yml

- Move ServeHTTPMetrics to serverutil
- Create separate metrics port for monitor
This removes the need to do an HTTPS health check

Serve HTTP metrics on separate port

---

cmd/keytransparency-monitor/main.go
cmd/keytransparency-sequencer/main.go
cmd/keytransparency-server/main.go
cmd/serverutil/listen.go
cmd/serverutil/serverutil.go

By moving TLS setup to the listener, we better isolate the crypto bits, and make things more API compatible with cmux.
Interesting Notes For Posterity:
- To support HTTP2, we need to explicitly ask for it in the `NextProtos` of the TLS config

Use TLS Listener

---

scripts/deploy.sh
scripts/docker-compose_test.sh
scripts/kubernetes_test.sh

Refer to the current commit hash every time.
This script results in incorrect hashes when HEAD moves after setting the
TRAVIS_COMMIT environment variable.

Set fresh  TRAVIS_COMMIT

---

cmd/serverutil/listen.go
scripts/gen_server_keys.sh

Removes the need to overwrite the host name

Add ipv6 localhost address to self-signed-cert

---

core/client/gobindclient/client.go
go.mod
go.sum

The last use of object hash was used to pin the config in the
gobindclient. Rather than hashing the config, future versions of the
client should either build in a static config, or supply it direclty

Remove objecthash dependency

---

cmd/keytransparency-monitor/main.go
cmd/keytransparency-sequencer/main.go
cmd/keytransparency-server/main.go
cmd/serverutil/listen.go
cmd/serverutil/serverutil.go
go.mod

Prioritize HTTP2 over HTTP1
Revert #1435 and use `http.ServeHTTP` rather than cmux.
- cmux prevents http.Serve from serving HTTP2
- http.Serve will only serve HTTP2 over TLS
- http.Serve uses a type assertion to validate this
- cmux interrupts this because it wraps the connection.
- even if the connection did come from a TLS listener 
The GCE ingress load ballancer requires services to serve 
an HTTP 200 OK at / on the same protocol that the server uses.
To support GRPC, this means using HTTP2 throuought.
HTTP2 also requires TLS, both by golang and GCE ingress.

Serve HTTP2 health check

---

deploy/kubernetes/base/monitor-deployment.yaml
deploy/kubernetes/base/sequencer-deployment.yaml
deploy/kubernetes/base/server-deployment.yaml
scripts/deploy.sh
scripts/kubernetes_test.sh

- Move Monitor key to it's own secret
- Move the TLS keys to a TLS secret
By moving the TLS certs into a proper kubernets tls secret, it can be read by an ingress object in the future.

Split kt-secrets into kt-tls and kt-monitor

---

.travis.yml
scripts/cleanup_images.sh
scripts/deploy.sh

Support running the cleanup script on both mac and linux.
gnudate on mac is `gdate`, while it is `date` on linux.
Also separate the cleanup script so deployments can be run in smaller steps.

Portable docker images cleanup script

---

README.md
cmd/keytransparency-client/cmd/root.go

This removes the need to pass `--insecure` because sandbox.keytransparency.dev
has a valid TLS certificate.

Use sandbox.keytransparency.dev as example server

---

README.md

The current install instructions fall back to non-module mode non-module
mode and result in incorrect dependencies.
Fixes #1390

GO111MODULE install directions

---

cmd/keytransparency-sequencer/main.go
core/sequencer/election/tracker.go
core/sequencer/election/tracker_test.go
internal/forcemaster/forcemaster.go

The previous NoopElection broke the API contract of the election factory
because it did not cancel contexts upon resigning. As a result, the KT
sequencer hung attempting to resign mastership.
This PR introduces a new `forcemaster.Election` which respects the election
API, and tests it against the `election.Tracker`.

ForceMaster election library

---

README.md

By using a fake authentication mechanism for the sandbox server we
achieve two objectives:
1. We can avoid making the authentication Google specific.
2. We can avoid the need to embed OAuth client secrets in open source
code. Client secrets are meant for particular compiled applications.
Fixes #1393 - Embed OAuth client ID

Use fake authentication in example

---

scripts/deploy.sh
scripts/kubernetes_test.sh

gcr.io does not consider 'latest' to be a valid docker tag,
so we must explicitly set one ourselves.

Set tags for init and prometheus docker images

---

core/sequencer/election/tracker_test.go

Avoid race condition in election test

Avoid race condition in election test

---

scripts/deploy.sh
scripts/kubernetes_test.sh
scripts/kustomize_image_tag.sh

This aids development by breaking the scripts into separate steps that can be run individually

Refactor: Move kustomize set image to it's own script

---

deploy/kubernetes/overlays/gke/cloudsql-sidecar.yaml

All pods were only declaring the 'cloud-sql-sidecar' service label, completely breaking service discovery

don't overwrite the ReplicaSet service label

---

deploy/kubernetes/base/kustomization.yaml
deploy/kubernetes/base/log-server-service.yaml
deploy/kubernetes/base/log-signer-service.yaml
deploy/kubernetes/base/map-server-service.yaml
deploy/kubernetes/base/monitor-service.yaml
deploy/kubernetes/base/prometheus-configmap.yaml
deploy/kubernetes/base/prometheus-deployment.yaml
deploy/kubernetes/base/prometheus-rbac.yaml
deploy/kubernetes/base/sequencer-service.yaml
deploy/kubernetes/base/server-service.yaml
deploy/prometheus/Dockerfile
docker-compose.override.yml
docker-compose.yml
scripts/kubernetes_test.sh
scripts/kustomize_image_tag.sh

The new prometheus config reads directly from the kubernetes API and annotations to discover what services to scrape for metrics. This removes the need to statically configure prometheus separately.

Upgrade Prometheus

---

impl/spanner/testutil/testutil.go

These functions create an in-memory spanner database with a specified DDL for testing. 
By setting a flag, the tests can be run against a real cloud spanner database as well.

Create spanner test helper funcs

---

.travis.yml
core/integration/storagetest/batch.go
core/integration/storagetest/mutation_logs.go
core/integration/storagetest/mutation_logs_admin.go
core/integration/storagetest/mutation_logs_reader.go
impl/integration/env.go
impl/memory/mutation_logs_test.go
impl/mysql/directory/storage_test.go
impl/mysql/mutationstorage/mutation_logs_test.go
impl/mysql/mutationstorage/mutations_test.go
impl/mysql/testdb/testdb.go
impl/mysql/testdb/testdb_test.go
impl/spanner/batch/batch_test.go
impl/spanner/directory/directory_test.go
impl/spanner/testutil/testutil.go

Go 1.14 introduced `t.Cleanup()`, eliminating the need to pass
callback cleanup functions throughout the testing infrastructure
as well as achieve better test cleanup reliability.

Use go1.14 t.Cleanup

---

impl/spanner/testutil/testutil.go

The various close operations all operate on the underlying connection, resulting in double and premature closing.

Don't double close grpc conn

---

README.md

`scripts/preare_server.sh` was replaced with  `$(go env
GOROOT)/src/crypto/tls/generate_cert.go` in #1447

Update README cert generation instructions

---

cmd/keytransparency-sequencer/main.go
cmd/keytransparency-server/main.go
cmd/serverutil/readyz.go
go.sum
impl/mysql/dberrors.go
impl/mysql/dberrors_test.go
impl/mysql/open.go
impl/storage.go

Support creating storage implementations of various types.

Storage Factory

---

core/sequencer/server.go

For all Map Revisions, we want each Map Revision written in the log of map
roots such that Map Revision == Leaf Index.
When Max Map Revision > Max Leaf Index, we want to AddSequencedLeaf all the
revisions inbetween.

Fix off by one error
